### ISSUE TITLE
Not able to run script

### ISSUE THREAD

**Issue by thisishere** [KovaaK/SensitivityMatcher#13]
I'm probably missing something simple but whenever I try to run the script it comes up with this error message.

![Script not running](https://user-images.githubusercontent.com/32013469/56214707-4bff7e80-6056-11e9-91e2-35b2bff9cc87.PNG)

**Comment by KovaaK** [comment]
That's what happens when people click Github's "Clone or Download" button...
![image](https://user-images.githubusercontent.com/7453399/56218222-93741380-6032-11e9-81f0-d79fadd02b75.png)
(I wish I could remove that)

Use this download button instead: 
![image](https://user-images.githubusercontent.com/7453399/56218262-a71f7a00-6032-11e9-92ec-2e55761d55b1.png)

https://github.com/KovaaK/SensitivityMatcher/releases/latest is the intended download link.
